# Workflow для сборки и деплоя Docusaurus в gh-pages

name: Deploy Docusaurus site from gh-pages branch

on:
  # Вручную или при пуше в gh-pages
  push:
    branches: ["gh-pages"]

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout ветки gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Установка зависимостей
        run: |
          npm install

      - name: Сборка сайта
        run: |
          npm run build

      - name: Проверка содержимого папки build
        run: |
          ls -la ./build

      - name: Копирование собранного сайта в ветку gh-pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Deploy Docusaurus site"
          git push origin gh-pages
